application: lanternctrl
version: portusers
runtime: python27
api_version: 1
threadsafe: true

handlers:
    - url: /.*
      script: app.app
      login: admin

libraries:
    - name: ssl
      version: "2.7"
